### ISSUE TITLE
Destruction of the editor when ViewCollection is adding children may end up in errors

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#203]
`ViewCollection.add( child )` returns a promise but it doesn't belong to `editor.create()` and `editor.destroy()` chain. So it is possible to destroy the editor when `ViewCollection.add( child )` promise is working (i.e. `child.init()` takes a long time to finish). 

Each promise created by `ViewCollection.add( child )` should be remembered in the property of the `VC` like `this._addPromises = [ promises for each add() ]` and removed from the array once resolved so when `ViewCollection.destroy()` is called, it should wait for `Promise.all( this._addPromises )` to finish.

A follow-up of https://github.com/ckeditor/ckeditor5-link/pull/104.

**Comment by Reinmar** [comment]
I believe @scofalik has recently run into this problem (and it might've been in the link tests). I think I was meant to report it but I can't see a ticket for that so... I'm glad you  run into this too :P

**Comment by Reinmar** [comment]
It seems that it was https://github.com/ckeditor/ckeditor5-link/issues/94.

**Comment by oskarwrobel** [comment]
Not exactly but It was our first thought too.  ckeditor/ckeditor5-link#94 was because I was trying to test asynchronous code by the synchronous test. The assertion was in the first event loop but the code was finishing asynchronous and the error occurred in the next events loop just after the test has finished. It has no impact to assertion but It was produced an error.
