### ISSUE TITLE
Prevent ContextualToolbar of being displayed in specific places

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#222]
I need to prevent `ContextualToolbar` of being displayed in some specific situation (when selection range intersects with some specific node). ATM `CT` displays always when the selection is non-collapsed and there is no way to configure it.

WDYT about adding `beforeShow` event to the `CT` plugin. This event will be fired after selection stops changing just before showing the toolbar. Other plugins will be able to listen to this event and modifies `CT` behavior eg by stopping this event what will prevent `CT` of being displayed?

**Comment by oleq** [comment]
A similar issue to https://github.com/ckeditor/ckeditor5-ui/issues/223 where the contextual balloon should not overlap the toolbar. IMO there should be a possibility to configure restricted zones (elements, in fact) which DOMRects should be avoided when positioning the balloon. 

This, with an addition of an event, because such restricted zones may be dynamic, would be very useful. Just note that such event would need to provide the proposed location of the balloon in the event data to make actual sense.

**Comment by oleq** [comment]
Or maybe I misunderstood: did you mean to analyze the editing view document tree or visual geometry of such tree elements?

**Comment by oskarwrobel** [comment]
In my case, I need to analyze position of selection in model document.
