### ISSUE TITLE
Make limiter element more configurable

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#260]
Let's assume that someone has a sticky header over the editable, and doesn't want to show BPV over the header and doesn't want to hide BPV under the header.

![image](https://user-images.githubusercontent.com/1057056/27538912-8f478f04-5a7a-11e7-8b1f-7a787175ba39.png)

There is no way to add sticky header height to the limiter top offset.

**Comment by fredck** [comment]
What if `[limiter top-offset] == [skicky header top-offset]`? I mean, the header is floating above the limiter?

For sure, having a limiter element is important as it covers many scenarios. Still, we may need to eventually provide configurable padding somehow, in the `[ top, right, bottom, left ]` format.

**Comment by oleq** [comment]
Since https://github.com/ckeditor/ckeditor5-utils/issues/157, you can define `target` as `Functions`. [`ContextualToolbar` uses this approach](https://github.com/ckeditor/ckeditor5-ui/blame/master/src/toolbar/contextual/contextualtoolbar.js#L226-L234).

All we need is to enable this thing for `limiter`. It's a 1LOC enhancement (+docs). Then, such function limiter function would be totally configurable and as specific as the implementation requires. For the case described by @oskarwrobel:

```js
limiter: () => {
    const limiterRect = new Rect( limiterElementInDOM );
    const stickyHeaderRect = new Rect( stickyHeaderInDOM );

    // Adjust the limiterRect to consider the stickyHeader. We could even 
    // introduce some sugar like Rect#substract() similar to existing Rect#getIntersection()
    limiterRect.top += stickyHeaderRect.height;
    limiterRect.height -= stickyHeaderRect.height;
    // etc.

    return limtierRect;
}
```

> Still, we may need to eventually provide configurable padding somehow, in the [ top, right, bottom, left ] format.

It would fail to meet more complex scenario requirements very soon. Then we'd be back exactly where we started. With the functional `limiter`, you can return any sort of `Rect`, e.g. in this case
```
  +--------------------------------------------+
  |                                            |
  |           The limiter element              |
  |                                            |
  |                                            |
  |     +--------------------------------+     |
  |     |                                |     |
  |     |     Some "taboo" zone          |     |
  |     |                                |     |
  |     +--------------------------------+     |
  |                                            |
  |                                            |
  |                                            |
  |                                            |
  +--------------------------------------------+
```
paddings would do no good but it's trivial case for `Rect` manipulation.

**Comment by oskarwrobel** [comment]
We need to:
- make possible to use function as limiter
- make possible to override default limiter for current balloons (`Link`, `ContextualToolbar`).
