### ISSUE TITLE
Support for binding styles to view model props

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#27]
So far we needed to something pretty ugly: https://github.com/ckeditor/ckeditor5/pull/152/files#diff-8141b614b20646bb5ecb4cd49dcb19eaR32

That needs to be improved.

**Comment by oskarwrobel** [comment]
So far I've implemented something like that:
```javascript
attributes: {
    style: {
        width: '100px',
        height: bind.to( 'height' )
    }
}
```
and works fine.

But.. here https://github.com/ckeditor/ckeditor5-ui-default/blob/master/src/list/listitemview.js#L36 I found a nice use case of style binding.

```javascript
attributes: {
    style: bind.to( 'style' )
}
```
I assume that we should support binding whole attribute instead of single styles because it might be useful. But how we want (if we wont) to do it?

```javascript
attributes: {
    style: bind.to( 'style' )
}

model.style = 'width: 100px; height: 100px';
```
or

```javascript
attributes: {
    style: bind.to( 'style' )
}

model.style = {
    width: '100px',
    height: '100px'
};
```

Second example looks better for me, but probably will be more complicated to implement because template binding works only (I might be wrong) for primitive types.

**Comment by oleq** [comment]
> I assume that we should support binding single styles and whole attribute as well because it might be useful. But how we want (if we want) to do it?

I see 2 options here:

## Easy one

If someone wants to bind the `style` attribute as a whole, 

```js
attributes: {
    style: bind.to( 'attr' )
}
```

then we enforce that `view.model.attr` must be a `String` to keep it simple, i.e.

```js
view.model = new Model( {
   ...
   attr: 'width: 100px; color: red;'
   ...
} );
```

## Hard one

We could implement nested `Model` attributes

```js
view.model = new Model( {
   ...
   attr: new Model( {
     width: '100px',
     color: 'red'
   } );
   ...
} );
```

and then use them in the `view.template`

```js
attributes: {
    style: bind.to( 'attr' )
}
```

which is more elegant and would allow changing specific style components (width, color, etc.) because the nested model `attr: new Model( { ... } )` fires proper (`change:width`, `change:color`, etc.) events.

The question is: does the editor need that? I don't think so or at least: not now. WDYT? 

// cc @Reinmar

**Comment by oskarwrobel** [comment]
I've already implemented easy option so I will create PR with it. If we decide to implement hard one we can create separate ticket.

**Comment by Reinmar** [comment]
I think that keeping styles in the model is a rare case and in fact quite a bad smell. In that specific case it makes sense, because how an option is rendered is actually its state and also needs to be fully configurable.

I'm not entirely sure what was already implemented and what's not, but if the dropdown's panel case is working on @oskarwrobel's PR, I'm ok with however it works. The main case, IMO, is if you bind a specific style to a specific model property and this should work best:

```js
attributes: {
    style: {
        width: '100px',
        height: bind.to( 'height' )
    }
}
```

(btw. height needs to have a 'px' appended)

**Comment by oskarwrobel** [comment]
> (btw. height needs to have a 'px' appended)

Do we want to add some magic that will be automatically appends `px` string after number value for some specific styles as width, height, border-width, border-radius etc?

**Comment by Reinmar** [comment]
I don't think so. Because we can't guess the units.

**Comment by oskarwrobel** [comment]
We can assume that if value is a Number then we add 'px' (px will be a default unit). If someone want to use different unit then value will be always a string.

```javascript
model = new Model( {
    width: '80%',
    fontSize: '2em',
    height: 200
} );
```

I think react works this way.

**Comment by oleq** [comment]
@oskarwrobel: It's too much magic. It will be a rare case that styles are controlled by the model. BTW, that's why it's possible to process the attribute's value in the callback:

```js
attributes: {
    style: {
        width: '100px',
        height: bind.to( 'height', h => `${ h }px` )
    }
}
```

**Comment by Reinmar** [comment]
I guess that some automation would be nice, but it's not necessary. There may be CSS props which accept numbers without units (line height) or don't accept px, so we would need to have a list of those. Let's better KISS. The main requirement for this UI framework is to be small.
