### ISSUE TITLE
Implement the toolbar dropdown that groups other buttons

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#333]
The component should look more or less like this:

![image](https://user-images.githubusercontent.com/1099479/32177636-1750c0d2-bd8b-11e7-8afd-2301d1df560c.png)

1. Should it have anything to do with the `DropdownView`?
1. What public API should it implement?
2. How should toolbar config deal with the component? Should we allow the toolbar config to group buttons in such way? I think not but maybe there's some smart way to translate the config to the group. There's the problem with configuring the icon and the behavior of the group button (action on click, state).
3. The button and the children must be accessible using the keyboard.

A follow–up of https://github.com/ckeditor/ckeditor5-alignment/issues/2.

**Comment by jodator** [comment]
I've fiddled a bit with dropdowns in Google Docs and:

They have two major types of such dropdowns buttons:

1. Button that upon click opens panel with options (may have state shown)
2. Split button that have two active parts - button and split icon.

Ad. 1.
- the button opens panel with other options (different alignment, size of panel)
- the button may or may not represent "active" state
- `enter`, `up arrow`, `down arrow` keys opens dropdown
- `arrows` allows to cycle through buttons on opened dropdown
- `escape` key close dropdown
- does not have "active" state - it rather change icon to reflect formatting in selection (ie alignment)

Examples:
Gmail text alignment:
![Gmail text alignment](https://user-images.githubusercontent.com/247363/32548492-1a8301dc-c486-11e7-98c4-9308347889ae.png)

Google docs line spacing:
![selection_008](https://user-images.githubusercontent.com/247363/32548527-3badfe3e-c486-11e7-8f5b-770c99eab56d.png)

Ad. 2.
- click on button executes command
- click on arrow opens dropdown
- `enter` on button executes command
- `enter` or `arrow up/dwon` on arrow opens
- `arrow`s inside dropdown selects options (arrow left on first item closes dropdown - but for me this is confusing)

Examples
Command active in selection:
![selection_009](https://user-images.githubusercontent.com/247363/32548579-713bbabe-c486-11e7-8bb0-38321f161fb0.png)

Focus on button part:
![selection_010](https://user-images.githubusercontent.com/247363/32548618-98f8e7b6-c486-11e7-9aa2-245a13397614.png)

Focus on arrow part:
![selection_011](https://user-images.githubusercontent.com/247363/32548620-9afe1b44-c486-11e7-8503-21848a9ce270.png)

Available options:
![selection_006](https://user-images.githubusercontent.com/247363/32549025-219e738c-c488-11e7-81ea-67c2cbd9bd35.png)

---
As I can see we could go with similar approach and implement both as:
- option 1 is simpler as it would group buttons and will change icon depending on which button is "on" (text alignment, headers).
- option 2 is more usable where you can invoke selected command like in highlight feature where arrow would let you define which highlighter to use and button would either highlight selected text or remove it selection.
---
As for questions:

> Should it have anything to do with the DropdownView?
For me it's direct child of dropdown view (at least option 1 that groups buttons).

> How should toolbar config deal with the component?
There's already [an issue for this](https://github.com/ckeditor/ckeditor5-ui/issues/322) with [details in here](https://github.com/ckeditor/ckeditor5-heading/issues/74#issuecomment-305224952).

The proposed way of grouping buttons to split button could be straightforward when:
- only one button can be active at the time (see alignment feature)
- whatever button is on it's icon is used for group
- probably `isEnabled` should be a function of all inner buttons

I think that in MVP taking an alignment and header buttons grouping we should implement `DropdownButtonGroup` first. The other `SplitButtonGroup` for me can have a bit different requirements and could be handled in separate issue.

So the `DropdownButtonGroup` should:
- accept collection of Buttons
- should change icon to whatever button is active
- could have config for inactive icon (or it should be defined which button is "default one")
- it might be the first button in collection otherwise
- on "enter"/"click" it should open dropdown to display all buttons

**Comment by jodator** [comment]
@oleq I'd made some prototype that binds `isEnabled` of child buttons to split button. Also the icon is bound to firts button that has `isOn = true`:

![screencast 2017-11-08 17_07_06](https://user-images.githubusercontent.com/247363/32559554-be6c83ba-c4a7-11e7-9ca1-fc7c3229104d.gif)

I'd go with this solution (grouping buttonViews not models) to enable such configurations later on:
```js
toolbar: [
    {
         type: 'dropdown',
         items: [ 'alignLeft', 'alignRight', 'alignCenter' ]
    }
]
```
as I understand this this would take toolbar items (` [ 'alignLeft', 'alignRight', 'alignCenter' ]`) and create dropdown button from them. WDYT?

**Comment by oskarwrobel** [comment]
This might be a kinda related topic https://github.com/ckeditor/ckeditor5-ui/issues/124.

**Comment by jodator** [comment]
Another POC of using ButtonViews: 

Adding 'alignments' toolbar component:
```js
// This might be later refactored as toolbar config
componentFactory.add( 'alignments', locale => {
	const buttons = styles.map( style => { 
		componentFactory.create( AlignmentEditing.commandName( style ) );
	} );

	return createButtonDropdown( buttons, locale );
} );
// then use:
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ArticlePluginSet, Alignment ],
		toolbar: [  'alignments' ] // or only buttons
	} )
```
Button behavior:
![screencast 2017-11-09 12_38_14](https://user-images.githubusercontent.com/247363/32603858-966d0692-c54b-11e7-8187-4d242143bb1c.gif)
Disabled state on image caption:
![screencast 2017-11-09 12_39_23](https://user-images.githubusercontent.com/247363/32603859-968bd27a-c54b-11e7-8e51-e158a28012b4.gif)

**Comment by oleq** [comment]
> As I can see we could go with similar approach and implement both as:
> 
> option 1 is simpler as it would group buttons and will change icon depending on which button is "on" (text alignment, headers).
> option 2 is more usable where you can invoke selected command like in highlight feature where arrow would let you define which highlighter to use and button would either highlight selected text or remove it selection.

I agree 👍.

# Plan

## First stage

**Let's focus on option1 first**. We need it ASAP for alignment. TBH, it boils down to [this old issue](https://github.com/ckeditor/ckeditor5-ui/issues/129).

Issue to resolve here:
* When using it for alignment, we expect the dropdown icon change as new alignment is chosen. But what about features that don't want anything to change when the items in the dropdown are selected (rough example below)?

    ![image](https://user-images.githubusercontent.com/1099479/32605764-ff5b8096-c552-11e7-8d3c-7a149bb16fd8.png)

   How should the component react? Should it detect if items are buttons with icons and act accordingly? How to configure the icon of the dropdown button in the above "font size" case?

   **To me, it sounds like a different component/configuration option. WDYT?** (cc @Reinmar)

## Second stage

Then [let's extend it for headers](https://github.com/ckeditor/ckeditor5-heading/issues/74). So developers can choose from:
1. a big dropdown with selected heading name (current implementation)
2. separate toolbar buttons (icons needed),
3. a compact dropdown like in this issue.

## Third stage

Option 2 will be needed by marker/highlight feature, so let's postpone it a little bit.

# Configurability

To KISS and speed up the development, in MVP, there will be no such thing as 

```js
toolbar: [
    {
         type: 'dropdown',
         items: [ 'alignLeft', 'alignRight', 'alignCenter' ]
    }
]
```
because it means more work with the toolbar configuration and `ComponentFactory` class etc.. Just the following (names to be determined) provided by the factory: 

```js
config: {
	toolbar: [ 'headingsDropdown', 'bold', 'italic', 'custombutton' ]
}
```
or
```js
config: {
	toolbar: [ 'headingX', 'headingY', 'headingZ', 'bold', 'italic', 'custombutton' ]
}
```
or
```js
config: {
	toolbar: [ 'headingsCompactDropdown', 'bold', 'italic', 'custombutton' ]
}
```

**Comment by jodator** [comment]
> When using it for alignment, we expect the dropdown icon change as new alignment is chosen. But what about features that don't want anything to change when the items in the dropdown are selected (rough example below)?

The demo above I've created with a new creature: `ButtonGroup` which simply gropus buttons and can have direction set (`isVertical`). It holds `ButtonViews` and should provide keystrokes handling for group (cycling, etc). Also it could be used as standalone (not in dropdown) - but maybe I'm overcomplicating things here).

Also I think that `buttonDropdown` might be "child" of different that `dropdownList` but both might have icon configurable to be either bound to active button or use "default one".

The `defaultIcon` might be usable also in a scenario when you define only two alignments (`center` and `justify`) but the default one `left` should be used as icon (either static either `default` when no button is active.

**Comment by jodator** [comment]
@oleq: my dev 'ButtonGroup' inside `DropdownPanel` with `isVertical=false`:

![selection_003](https://user-images.githubusercontent.com/247363/32607050-e6967ea8-c557-11e7-9292-47c9224a0b3d.png)

Also a case for `defaultIcon` for dropdown to have.
