### ISSUE TITLE
Why the blockquote icon is reversed

### ISSUE THREAD

**Issue by wenmingtang** [ckeditor/ckeditor5-ui#347]
ckeditor:
<img width="86" alt="wx20171129-100229 2x" src="https://user-images.githubusercontent.com/1620172/33354166-6e4d572e-d4ec-11e7-9dc5-2afc07d90d83.png">

other editors:
<img width="55" alt="wx20171129-100135 2x" src="https://user-images.githubusercontent.com/1620172/33354155-6371c3ee-d4ec-11e7-99c6-da223afbf690.png">

**Comment by jodator** [comment]
Hi, interesting question since there are [many](https://en.wikipedia.org/wiki/Quotation_mark) [styles](https://www.translatemedia.com/translation-blog/punctuation-in-different-languages/) for defining quotation marks.

As most of us working on CKEditor are from Europe it probably happened that we used quotation marks used in [Central Europe](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table) for the icon.

ps.: In some discussion it turned out that we might change icons styles depending on editor language (or by edited content) so for US and other countries using reversed quations it might be `“`, the `”` might be used for most European languages and `»` for other languages (like Arabic). As for now we provide icons that should be internationally recognised.

**Comment by oleq** [comment]
This issue will be handled in https://github.com/ckeditor/ckeditor5/issues/645.

**Comment by wenmingtang** [comment]
@oleq Thanks.

**Comment by oleq** [comment]
This is what it looks like after the re-design
![image](https://user-images.githubusercontent.com/1099479/35798159-454b96a0-0a62-11e8-84ae-932021cdbea6.png)
