### ISSUE TITLE
Allows passing context to Template.bind

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#45]
I would allow functions like [this](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/editableui/inline/inlineeditableuiview.js#L33-L35) to become methods of the class. At the moment it's not possible because there's no way to pass `this` context into such binding.

It could simply be

```js
foo: bind.to( 'name', this._getLabel, this ),
```

**Comment by Reinmar** [comment]
But there's no `this` used inside that function.

**Comment by Reinmar** [comment]
Actually – I removed the `TODO` comment that was there just yesterday, because it was saying that such a feature is needed. But the `t()` function should not be used with `this`. 

If there was a need to use `this` in such a callback then you can still solve this by using an arrow function directly inside `bind.to()`. Since ES6 passing context to a those kind of functions makes little sense usually.

PS. The reason why `getLabel` is defined outside of `bind.to()` is that it's used twice.

**Comment by oleq** [comment]
Yes, it's used twice but it is also created for each instance of the class. We should rather declutter constructors and memory.

BTW: It will become a common case that the context is needed. Imagine lengthy event listeners with a very complex logic (like `onkeydown` in some autocompleter). They will certainly become class methods and will need context to work properly.

```js
on: {
  keydown: bind.to( this._handleThisMess, this )
}
```

**Comment by Reinmar** [comment]
Don't worry about memory. Really. Not at this stage and in this case... I guess, never. 

In the second case:

```
on: {
    keydown: bind.to( () => this._handleThisMess() )
}
```

We do this already in couple of places.

**Comment by oleq** [comment]
```js
on: {
    keydown: bind.to( () => this._handleThisMess() )
}
```

is some solution. That's true. So let's wait and write some more components. Then we'll decide.

**Comment by Reinmar** [comment]
We removed the ctx param from the event emitter, so let's not add it here.
