### ISSUE TITLE
TypeError: this.element.querySelectorAll(...).forEach is not a function

### ISSUE THREAD

**Issue by FiShelly** [ckeditor/ckeditor5-ui#461]
I create a es5 build of CKEditor 5. (inline-editor).

And I use it in vue project, when i visit my app in firefox43, the broswer will throw error.

```
TypeError: this.element.querySelectorAll(...).forEach is not a function
```

so, how to solve it? 

By the way, Is ckeditor support firefox43 ,chrome48?

thx.

**Comment by jodator** [comment]
Looks like it is available since Firefox 50: https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach.

**Comment by jodator** [comment]
As for [compatibility](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/browser-compatibility.html#desktop-environment) it is always latest browser version.

**Comment by FiShelly** [comment]
> As for [compatibility](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/browser-compatibility.html#desktop-environment) it is always latest browser version.
> 
> ps. Out of curiosity I've checked that [Firefox 43](https://www.mozilla.org/en-US/firefox/43.0/releasenotes/) is more then 3 years old.

thx for your help.

emmm..., you are right, Firefox 43 is more then 3 years old.

But, our company's products still have to support it. 

so i must try to make ckeditor support .

By the way, do you have any way to make it support  Firefox 43?

I try to modify the source code, ant it fixed this error, but the ckeditor is not working properly.

firefox43 in window:
![image](https://user-images.githubusercontent.com/16427792/51249618-cd4f6280-19ce-11e9-881d-a56665f1b058.png)

chrome71 in macos:
![image](https://user-images.githubusercontent.com/16427792/51249678-f1ab3f00-19ce-11e9-9962-6e2f17036557.png)

the console is not throw any error.

**Comment by jodator** [comment]
I've checked the code and the only thing I've found was this part:

https://github.com/ckeditor/ckeditor5-ui/blob/102e25aaab48eb3798b023c244cd19ac6321cacc/src/icon/iconview.js#L121

I've also checked that alternative:
```js
Array.from( this.element.querySelectorAll( '.ck-icon__fill' ) ).forEach( path => {
	path.style.fill = this.fillColor;
} );
```
does work in latest Firefox/Chrome. Unfortunately I don't know what exactly changed since FF 43 and I don't know what other parts of CKEditor code base needs adjustments to make editor compatible with FF 43. General notes: I'd try to run the editor with [minimal set of plugins (by editing a build)](https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js#L34-L56) (probably `Essentials` and `Paragraph` should be enough) only and enable adding other features one by one (start with `Bold` for instance). Ideally by creating a [custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html). 

If you have CKEditor license, please contact our support team. You also can ask your questions at Stack Overflow.

**Comment by FiShelly** [comment]
> I've checked the code and the only thing I've found was this part:
> 
> [ckeditor5-ui/src/icon/iconview.js](https://github.com/ckeditor/ckeditor5-ui/blob/102e25aaab48eb3798b023c244cd19ac6321cacc/src/icon/iconview.js#L121)
> 
> Line 121 in [102e25a](/ckeditor/ckeditor5-ui/commit/102e25aaab48eb3798b023c244cd19ac6321cacc)
> 
>  this.element.querySelectorAll( '.ck-icon__fill' ).forEach( path => { 
> I've also checked that alternative:
> 
> ```js
> Array.from( this.element.querySelectorAll( '.ck-icon__fill' ) ).forEach( path => {
> 	path.style.fill = this.fillColor;
> } );
> ```
> 
> does work in latest Firefox/Chrome. Unfortunately I don't know what exactly changed since FF 43 and I don't know what other parts of CKEditor code base needs adjustments to make editor compatible with FF 43. General notes: I'd try to run the editor with [minimal set of plugins (by editing a build)](https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js#L34-L56) (probably `Essentials` and `Paragraph` should be enough) only and enable adding other features one by one (start with `Bold` for instance). Ideally by creating a [custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html).
> 
> If you have CKEditor license, please contact our support team. You also can ask your questions at Stack Overflow.

ok, thank for you help.
