### ISSUE TITLE
Inactive buttons get outline on mousedown

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor5-ui#473]
Inactive buttons are outlined when user hold mouse down over it.
![Mar-21-2019 09-49-24](https://user-images.githubusercontent.com/9017322/54741409-aaa01c80-4bbe-11e9-8baa-057324dc055b.gif)

1. Open page with CKEditor5: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
2. Move cursor over undo/redo buttons.
3. Hold down LMB over button.

I suspect that inactive buttons should get `disabled` attribute, to not have possibility to interact with them.

**Comment by jodator** [comment]
I'm not sure if this is a bug or deliberate feature to allow keyboard navigation and a11y. You can (and AFAIR you should) focus the disabled button and the screen reader would announce that button.

That's why the disabled button is outlined on focus which happens also when you click it.

/cc @oleq to confirm that

**Comment by oleq** [comment]
AFAIR it's an a11y feature. Since we allow focusing disabled buttons using the keyboard (predictability for screen reader users), we allowed that using mouse too (not sure we could do the first and disallow the later anyway).
